version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app-network

  #Nginx
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8081:80"
#      - "443"
    volumes:
      - ./:/var/www
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  #Redis
  redis:
    image: redis:6.0.9
    container_name: redis
    restart: unless-stopped
    tty: true
    ports:
      - "6380:6379"
    volumes:
      - ./.docker/data/redis/:/data
    networks:
      - app-network

  #Scheduler
  scheduler:
    image: digitalocean.com/php
    command: "./.docker/bin/run-scheduler.sh"
    container_name: scheduler
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app-network

  #Worker
  worker:
    image: digitalocean.com/php
    command: "./.docker/bin/run-worker.sh"
    container_name: worker
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
